
[phases.setup]
nixPkgs = ['nodejs-18_x', 'python310']

[phases.install]
cmds = [
  'npm ci',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

